config:
  mean:
    - 0.406
    - 0.456
    - 0.485
  std:
    - 0.225
    - 0.224
    - 0.229
  type: "fp32"

load_onnx:
  inputs:
    - x
  input_size_list:
    -
      - 1
      - 3
      - 112
      - 112
  outputs:
    - save_infer_model/scale_0.tmp_1

build:
  do_quantization: True
  dataset: ./dataset.txt