config:
  mean:
    - 0.5
    - 0.5
    - 0.5
  std:
    - 0.5
    - 0.5
    - 0.5

load_onnx:
  inputs:
    - x
  input_size_list:
    -
      - 1
      - 3
      - 224
      - 224
  outputs:
    - p2o.save_infer_model/scale_0.tmp_0.0

build:
  do_quantization: false
  dataset: