load_onnx:
  inputs:
    - x
  input_size_list:
    -
      - 1
      - 3
      - 224
      - 224
  outputs:
    - Add.53

config:
  # BGR
  mean:
    - 0.406
    - 0.456
    - 0.485
  std:
    - 0.225
    - 0.224
    - 0.229
  type: "fp32"

build:
  do_quantization: True
  dataset: ./dataset.txt