config:
  mean:
    - 0.406
    - 0.456
    - 0.485
  std:
    - 0.225
    - 0.224
    - 0.229

load_onnx:
  inputs:
    - image
  input_size_list:
    -
      - 1
      - 3
      - 320
      - 320
  outputs:
    - split_0.tmp_1
    - split_1.tmp_1
    - split_2.tmp_1
    - split_3.tmp_1
    - sigmoid_0.tmp_0
    - sigmoid_1.tmp_0
    - sigmoid_2.tmp_0
    - sigmoid_3.tmp_0

build:
  do_quantization: false
  dataset: