config:
  mean:
    - 0.406
    - 0.456
    - 0.485
  std:
    - 0.225
    - 0.224
    - 0.229

load_onnx:
  inputs:
    - image
  input_size_list:
    -
      - 1
      - 3
      - 320
      - 320
  outputs:
    - p2o.DequantizeLinear.1705
    - p2o.DequantizeLinear.1707
    - p2o.DequantizeLinear.1619
    - p2o.DequantizeLinear.1621
    - p2o.DequantizeLinear.1533
    - p2o.DequantizeLinear.1535
    - p2o.DequantizeLinear.1445
    - p2o.DequantizeLinear.1447

build:
  do_quantization: false
  dataset: