load_onnx:
  inputs:
    - input0
  input_size_list:
    -
      - 1
      - 3
      - 320
      - 320
  outputs:
    - output0
    - /Concat_1_output_0
    - 592

config:
  # RGB
  mean:
    - -104
    - -117
    - -123
  std:
    - 1
    - 1
    - 1
  type: "int8"
  quantized_algorithm: normal
  quantized_dtype: w16a16i
  optimization_level: 0

build:
  do_quantization: True
  dataset: ./dataset.txt