config:
  mean:
    - -104
    - -117
    - -123
  std:
    - 1
    - 1
    - 1
  type: "int8"

load_onnx:
  inputs:
    - image
  input_size_list:
    -
      - 1
      - 3
      - 320
      - 320
  outputs:

build:
  do_quantization: false
  dataset: